name:                rowdy-yesod
version:             0.0.1.0
github:              parsonsmatt/rowdy
license:             BSD3
author:              Matt Parsons
maintainer:          parsonsmatt@gmail.com
copyright:           2018 Matt Parsons

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            An EDSL for web application routes.
category:            Web
description:         Please see the README on Github at <https://github.com/parsonsmatt/rowdy#readme>

dependencies:
- base >= 4.7 && < 5
- yesod-core 
- mtl
- dlist

library:
  source-dirs: src

tests:
  specs:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rowdy
    - hspec
